### ISSUE TITLE
Argument validation failure results in process exit status 0

### ISSUE THREAD

**Issue by whchapman** [danielrayali/sargs#28]
If Initialize(int argc, char* argv[]) fails, and _exit_enabled is true, the exit status for the process is 0.

The exit status should be nonzero, or user-configurable, so parent processes can correctly determine that a child process has failed due to an argument error.

**Comment by danielrayali** [comment]
Closing as could not reproduce. Some updates have been applied. Feel free to re-open if there is a specific situation.
